/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { RangeRequestsPlugin } from 'workbox-range-requests';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite (HTML, JS, CSS, WASM)
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Cache PMTiles (Range Requests supported)
registerRoute(
  ({ url }) => url.pathname.endsWith('.pmtiles'),
  new CacheFirst({
    cacheName: 'pmtiles-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200, 206] }),
      new RangeRequestsPlugin(),
    ],
  })
);

// 2. Cache Parquet Files (Range Requests supported for DuckDB-Wasm)
registerRoute(
  ({ url }) => url.pathname.endsWith('.parquet'),
  new CacheFirst({
    cacheName: 'parquet-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200, 206] }),
      new RangeRequestsPlugin(),
    ],
  })
);

// Allow forced updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
